name: Demo ci-cd
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: run unit tests
        run: go test ./...

      - name: echo success
        run: echo "Success!!"