name: Staging CI
on:
  push:
    branches: [ stage ]

jobs:
  # Checkout and install golang
    tests:
      runs-on: ubuntu-20.04
      steps:
       - name: "Checkout code"
         uses: actions/checkout@v3

       - name: "install golang"
         uses: actions/setup-go@v3
         with:
           go-version: 1.18

       - name: "run unit tests"
         run: go test ./...

    build:
      runs-on: ubuntu-latest
      environment: "stage"
      needs: tests
      steps:
        - uses: actions/checkout@v3

        - name: "Build App Image"
          run: docker build -f ./docker/Dockerfile -t sonyamoonglade/ci_cd_app:latest .

        - name: "login to docker hub"
          run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --password-stdin --username sonyamoonglade

        - name: "push recently built image to registry"
          run: docker push sonyamoonglade/ci_cd_app:latest

    remote_deploy:
      runs-on: ubuntu-latest
      environment: stage
      needs: build
      steps:

        - name: "clone docker-compose file to action runner"
          run: git clone "https://${{ secrets.GIT_ACCEESS_KEY }}@github.com/sonyamoonglade/ci-cd-go-deployment" .

        - uses: actions/checkout@v3

        - name: "copy files with scp"
          uses: appleboy/scp-action@master
          with:
            host: 51.250.101.164
            username: aalexandrovich
            key:  -----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAtEawhHP XDTrSPl3GqXSD/AAAAEAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQC9S0PP6z/B iKkZp8cT/eonNY3EcjlCfGQFEcflGJesNAEvRx9SkuLO7oBhEk0AgCdkAFyMF1k0ZSq2Kn GPift7zrWStUM6R13aQBeso37gt8KKhjPZ6ihAf41YLyd1gU66oCqXLxF6Jnu6JBNb4Hrx mtnyI4X30ba/KHzZyJk4/bGeMLlxk79Ptr5ctRlTCn2fKVLBMMHIzmHyV3BTh+pMVNVuny +QJN8BFfoDOsZ6StP8aSWDre4w+b+TbywjIL3xzV8pTwzItc15LXlZOJ7V1o+IeKZi2Umu 79aoxwRM3Gj7AfCgVTY3mxZ6/LxD+8sAS9h6lNiYmm4jHQBKhbgDAAAD4CP42unV+12hK1 AqaMmJAukJDvaLtHY36dtSCWXTwzo/nVl6xWJeqz1IvsqouFXIBVbtUXy/jsJWAMWfQupG dyT8xYFX7NLIzvTl7mTxT7vhweGVxkgARChkxNfeqg6B7ZlzaPUlT8UpT7BGUTLSfMSTOO uCZHi/NJNXHoW03ZIqROzlKrsQX+XjAZNB7iO+7Cs4611uE8RchY2aSe1wRtyripUYgPTk ST3Xi5Lp/BMQTazghTtGmFr0xUNpOJQ3rikjIBdkV7fANPcCXvP7Gek5saMHIcbZTa8qNe /0S7SaAqPX5vVfxcI26JMa7dx41bTf+0MtkMtLA/zCSRSBK8ioAyT8ZA6ktjRPFM6hfIzT mUrUjQApbvgx+pUkAyvRrSJbOcHmuKrINkhhmrre1uHm4GYIg0Tv4uAy2V/i8NgcPpys+B 20GMZdfcGSJCtPuewGtJl0yKa9QyW/CJ+A2sZ1n22is9c27RnTaaZIPABQS+wAAoKAhfV7 A+PO62bLeHQN73zo/WnDE79Z/tCl5dwOwLXXzgudgxg2Y7qFI8PwQHO9BrGARoByA6XhTw qUNnKKrUwsbcu6CpwIol3pSW0c3vnG1Rn/6O73z9UUNgNJYXmHbjcvzYUVGrSzmFi88BLB 6063bsp6gQFNiCEFQndeOjFG+jvemwT6Jc77UDkym6XTZUlCo8R0n7Q6BNK+FX3uWeRz0l X04zA6hozBNa0eiFjMA0/wkzGVi1tsNZu7jVWsw8pIcESqPsk+IZXmrt63oNSB/HDAr4Bz 1J/WG/oef7zx0Xeezc7EKUwlspMlh/1E9hDTUhpk7g5DMgdD4WZ5SnKuqbbUzBCNS+po2b Cx8NUtdIqnq07Nhf+mnDdghY1eXwsq/lfffESREHIW8dG8BMS8QF2CAnWPa6WD34ZYyOx/ WU+ZGqFdwvKcFB6HnP7pcdvzzY8WN6BgXEgXyiSg1JmxO11ywEXSDcwtwCxyh6wqGA3uYg mh1WtpiZ1XzRpjJR832+Zg4wygtzTJXoKDR4NMGcjefIWluNWcJYVERVoy8Y6TXGiqYzKY BvPZ888htExQLSHobrepofcqm5LTkM3nNFXL3rDr+oP0jAOHLKpvGhLiHBlXXDAfUChuh4 ZosO0OQ9IPcuJyTAzr+TwmECyVBWTN/ugWN7HTxK+vHfxNG+m054svuItnVHq3I9em1DeL 4XiQjggtF3ZgkE1KLD7nDdDFbwTUkWAks24wRuiK6zU3WWrQaOeo3E2Jd8h+eqx3f94eUE 8Tynw+M8mERtQTVP4F3bxIMcDa8XFW6oI+QvMJOzr5iRA1joz0 -----END OPENSSH PRIVATE KEY-----
            source: "migrations/,./docker-compose.yaml,./setup.sh"
            passphrase: ${{ secrets.VM_SSH_PASSPHRASE }}
            target: "./"

        - name: "hop onto vm via ssh and refresh containers"
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.VM_SSH }}
            script: |
              export DB_PWD="${{ secrets.DB_PWD }}"
              export DB_HOST="${{ secrets.DB_HOST }}"
              export DB_USER="${{ secrets.DB_USER }}"
              export DB_PORT="${{ secrets.DB_PORT }}"
              export DB_NAME="${{ secrets.DB_NAME }}"
              export DATABASE_URL="${{ secrets.DATABASE_URL }}"

              sudo chmod +x ./setup.sh

              ./setup.sh
