name: Staging CI
on:
  pull_request:
    branches: [stage]

jobs:
  # Checkout and install golang
    tests:
      runs-on: ubuntu-20.04
      steps:
       - name: "Checkout code"
         uses: actions/checkout@v3

       - name: "install golang"
         uses: actions/setup-go@v3
         with:
           go-version: 1.18

       - name: "run unit tests"
         run: "go test ./..."
    build:
      runs-on: ubuntu-20.04
      needs: tests
      steps:
        - name: "Build App Image"
          run: "docker build -f ./../../docker/Dockerfile -t sonyamoonglade/ci_cd_app:latest" .

        - name: "login to docker hub"
          run: "echo (${{ secrets.DOCKER_HUB_PASSWORD }}) | docker login --password-stdin --username sonyamoonglade"

        - name: "push recently built image to registry"
          run: "docker push sonyamoonglade/ci_cd_app:latest"
